- name: installing nginx
  hosts: localhost
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: nginx service
    ansible.builtin.service:
      name: nginx
      state: started
